### ISSUE TITLE
Some problem with comments

### ISSUE THREAD

**Issue by kitesurf** [ugurozturk/instabot.pyV2#32] opened 2018-01-10 08:37 UTC
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [X ] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [X ] Searched and checked other issues about my problem
- [X ] If have errors.log file and i did upload it

Check One :
- [X ] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
Linux, Ubuntu 16.04
## Python Version ?
2.7
## Is it VPS ?
no
### VPS: Is the vps far far away ? Another Country ?
Yes / No
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10
1.. I understand some errors
I'm using 30 comments per day
here my error in console: 

> Traceback (most recent call last):
  File "example.py", line 72, in <module>
    bot.new_auto_mod()
  File "/home/daniel/Progys/instabotV2/src/instabot.py", line 691, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/daniel/Progys/instabotV2/src/instabot.py", line 759, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/home/daniel/Progys/instabotV2/src/instabot.py", line 783, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ugurozturk** [comment] 2018-01-10 12:51
@kitesurf is your code really updated ?

**Comment by ugurozturk** [comment] 2018-01-10 12:53
@kitesurf duplicate of https://github.com/ugurozturk/instabot.pyV2/issues/22. And do update your code before sending issue. You code also looks old.

**Comment by ugurozturk** [comment] 2018-01-10 12:54
https://github.com/ugurozturk/instabot.pyV2/archive/masterv2.zip

**Closed by ugurozturk** 2018-01-10 12:53 UTC
