### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by eastcoastboys** [ugurozturk/instabot.pyV2#21] opened 2018-01-04 21:52 UTC
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [ X] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [ X] Searched and checked other issues about my problem
- [X ] If have errors.log file and i did upload it

Check One :
- [ X] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
 Windows 
## Python Version ?
2.7
## Is it VPS ?
Not Sure
### VPS: Is the vps far far away ? Another Country ?
Not sure

## What is your python knowledge vote 0/10
4

Issue: 
1) The bot had failed while commenting, the error that had come up was an error that the "No JSON object could be decoded"

2) I have gotten a "Not Liked: 400" error today for the first time.

[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1604824/errors.log)

**Comment by ugurozturk** [comment] 2018-01-05 11:01
duplicate of https://github.com/ugurozturk/instabot.pyV2/issues/22

**Comment by ugurozturk** [comment] 2018-01-05 11:01
i am marking this duplicate because the issue 22 has better tracking errors.

**Closed by ugurozturk** 2018-01-05 11:01 UTC
