### ISSUE TITLE
alueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by leandrodlorenzo** [ugurozturk/instabot.pyV2#10] opened 2018-01-03 07:26 UTC
Hi i have this problem, can you help me?

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "check_status.py", line 3, in <module>
    from .user_info import get_user_info
ValueError: Attempted relative import in non-package

**Comment by joby8** [comment] 2018-01-03 08:47
yes, i have got the same problem. But i can't help. sorry

**Comment by mmming** [comment] 2018-01-03 08:49
Have the same issue.(

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

**Comment by viveksb007** [comment] 2018-01-03 09:48
just goto src directory and remove '.' from every import statement
Like if its "from .user_info import get_user_info" change it to "from user_info import get_user_info"
This would solve import issue.

**Comment by ugurozturk** [comment] 2018-01-03 11:52
made new commit. Forgotten example.py broke this. And duplicate of #7

**Closed** 2018-01-03 11:53 UTC
Labels: duplicate
